"""init schema

Revision ID: 8e5e5500c166
Revises: 
Create Date: 2025-12-12 22:38:23.900823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5e5500c166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_slug'), 'nodes', ['slug'], unique=True)
    op.create_table('edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('requires', 'recommended', name='edge_type'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dst_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_id', 'dst_id', 'type', name='uq_edge_src_dst_type')
    )
    op.create_index(op.f('ix_edges_dst_id'), 'edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_edges_src_id'), 'edges', ['src_id'], unique=False)
    op.create_table('related_edges',
    sa.Column('a_id', sa.Uuid(), nullable=False),
    sa.Column('b_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('a_id < b_id', name='ck_related_canonical_order'),
    sa.ForeignKeyConstraint(['a_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('a_id', 'b_id'),
    sa.UniqueConstraint('a_id', 'b_id', name='uq_related_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_edges')
    op.drop_index(op.f('ix_edges_src_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_dst_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_nodes_slug'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
